### ISSUE TITLE
Ibdesignable not working correctly through Carthrage.  

### ISSUE THREAD

**Issue by phongleq** [hsousa/HCSStarRatingView#31]
There seems to be a issue when trying to preview the view with the framework using carthage. Mine fails to render and complains that the target is missing.

**Comment by hsousa** [comment]
I'm sorry, but I don't use Carthage (support was added via pull request). If you have any idea on how to fix with this feel free to either ping me to discuss or submit a PR.

**Comment by Benuuu** [comment]
I think I'm running into the same issue in my xib.  The project is using Swift and Cocoapods.

`FILENAME.xib: warning: IB Designables: Using class UIView for object with custom class because the class _TtC11DealerRater17HCSStarRatingView does not exist`

My view's Identity Inspector Shows:
```
Custom Class:
    Class: HCSStarRatingView
    Module: Blank (aka. Current)
```

@phongleq are you seeing the same warning?

**Comment by hsousa** [comment]
Closing this as it's been dead for a while. Please reopen if you have feedback on this issue.
