### ISSUE TITLE
Custom Image

### ISSUE THREAD

**Issue by kyominoh** [hsousa/HCSStarRatingView#36]
Hi, bro 

I have a problem with RatingView that u posted on Github.

I applied the following source to use a different image, not the existing star image, as you wrote.

starRatingView.emptyStarImage = [UIImage imageNamed:@"heart-empty"]; //like_off_big.png
starRatingView.filledStarImage = [UIImage imageNamed:@"heart-full"];//like_on_big.png

I could see the new image that I put in on RatingView, but when I tried to run RatingView, apps crash. (touched RatingView)

The reason for the crash is 

[UIImage renderingMode]: message sent to deallocated instance 

I used call stack and figured out the following code occurred the error. 

 [self _drawStarWithFrame:frame tintColor:self.tintColor highlighted:highlighted]; in drawRect:(CGRect)rect 

Could you please let me know how to solve this problem? 

Thank you.

**Comment by kyominoh** [comment]
i try to storyboard, but apps are crash

**Comment by hsousa** [comment]
Hi @kyominoh!

I find that very strange, because those properties are `strong`.

Can you share a simple sample project where that happens? (you can zip it and paste the dropbox link here)

**Comment by kyominoh** [comment]
https://www.dropbox.com/s/7qwa133kmjmx2xd/KKariPeopleFixMe.zip?dl=0

Here is a simple source
Full source can not share, sorry
And Sorry to bother

**Comment by hsousa** [comment]
The problem is that you're **not** using ARC, so when you do this:

```objective-c
_ratingView.filledStarImage = [[UIImage imageNamed:@"like_off_big"] imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
```

I'm doing this:

```objective-c
- (void)setFilledStarImage:(UIImage *)filledStarImage {
    if (_filledStarImage != filledStarImage) {
        _filledStarImage = filledStarImage;
        [self setNeedsDisplay];
    }
}
```

As you can see, my code is ARC-only (ie. I'm not retaining anything because ARC does that for me) and you just provided that setter an autoreleased object. That means that the object will get released on the next runloop, resulting in the error you're seeing.

My advice is to get on the ARC boat, since it's awesome... but if you _must_ stay away from ARC, add the `-fobjc-arc` flag to `HCSStarRatingView.m` so at least _that_ gets compiled with ARC enabled.

Please note that you will have the exact same type of problems if you use a lot of other controls from GitHub, since almost all of them require ARC nowadays (but you can definitely use the flag approach above for other controls).

For reference, this is where you need to add the flag:
![screen shot 2016-03-04 at 13 03 17](https://cloud.githubusercontent.com/assets/2064882/13527783/7a767184-e209-11e5-869d-190d2f5859e6.png)

**Comment by kyominoh** [comment]
Thanks Bro,
I forgot to develop again in two years
i'm fool ㅠ.ㅠ

**Comment by hsousa** [comment]
No worries man, glad I could help. :+1:

**Comment by kyominoh** [comment]
thanks shared source
Very well've used them
Good luck
